import { test, expect } from '@playwright/test'

test('built SPA: registration, profile, trip, checklist persistence and account isolation', async ({ page, browser }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/register')
  await page.getByLabel('邮箱').fill(`container-${Date.now()}-${info.project.name}@example.com`)
  await page.getByLabel('密码', { exact: true }).fill('local-test-only-123')
  await page.getByRole('button', { name: '注册', exact: true }).click()
  await expect(page.getByRole('button', { name: '退出', exact: true })).toBeVisible()
  await page.goto('/profile')
  await page.getByLabel('孩子小名').fill('测试勇士')
  await page.getByLabel('城市', { exact: true }).fill('虚构城市')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByText('已保存', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('孩子小名')).toHaveValue('测试勇士')
  await page.goto('/plan/2026-10-04_container-demo')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('容器验证示例')
  await page.getByRole('button', { name: '创建本次出行计划' }).click()
  const gear = page.locator('#gear input[type=checkbox]').first()
  const task = page.locator('#tasks input[type=checkbox]').first()
  await gear.click()
  await expect(gear).toBeChecked()
  await expect(gear).toBeEnabled()
  await task.click()
  await expect(task).toBeChecked()
  await expect(task).toBeEnabled()
  await page.reload()
  await expect(gear).toBeChecked()
  await expect(task).toBeChecked()
  const tripUrl = page.url()
  await page.screenshot({ path: info.outputPath('container-trip.png'), fullPage: true })

  const other = await browser.newContext()
  const guest = await other.newPage()
  await guest.goto(tripUrl)
  await expect(guest.getByRole('heading', { name: '登录', exact: true })).toBeVisible()
  await other.close()
  expect(errors).toEqual([])
})
