import { test, expect } from '@playwright/test'

test('archive filtering and controlled drawer interaction', async ({ page }, testInfo) => {
  await page.goto('/e2e/components.html')
  await expect(page.getByRole('link', { name: /山野备用计划/ })).toHaveAttribute('href', '/plan/archive')
  await expect(page.getByText('非归档计划')).toHaveCount(0)
  await expect(page.getByRole('region', { name: '安全口诀' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('components.png'), fullPage: true })
  const trigger = page.getByRole('button', { name: '打开成就面板' })
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: '成就面板' })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByText('徽章内容')).toBeVisible()
  await page.getByRole('tab', { name: /足迹/ }).click()
  await expect(dialog.getByText('足迹内容')).toBeVisible()
  await expect(dialog.getByText('徽章内容')).toBeHidden()
  await page.screenshot({ path: testInfo.outputPath('drawer.png'), fullPage: true })
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
  await expect(trigger).toBeFocused()
  await trigger.click()
  await dialog.getByRole('button', { name: '关闭成就面板' }).click()
  await expect(dialog).toBeHidden()
  expect(await page.evaluate(() => document.body.style.overflow)).toBe('')
})

test('drawer tabs support keyboard navigation and modal focus', async ({ page }) => {
  await page.goto('/e2e/components.html')
  await page.getByRole('button', { name: '打开成就面板' }).click()
  const badges = page.getByRole('tab', { name: /徽章/ })
  await badges.focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab', { name: /足迹/ })).toBeFocused()
  await expect(page.getByText('足迹内容')).toBeVisible()
  await page.keyboard.press('Home')
  await expect(badges).toBeFocused()
  await expect(page.getByText('徽章内容')).toBeVisible()
})
